my_project:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: XY27110
      user: snowprouser
      password: Chanti@22Monday
      role: PC_DBT_ROLE
      database: PC_DBT_DB
      warehouse: PC_DBT_WH
      schema: tr
